import { Color, colors, Card, Deck, cardPoints, createDeck, createDeckFromMemento, createInitialDeck } from './deck'
import { Shuffler, standardShuffler } from '../utils/random_utils'
export type Direction = 'clockwise'|'counterclockwise'
export type RoundMemento = {players:string[],hands:any[][],drawPile:any[],discardPile:any[],currentColor:Color,currentDirection:Direction,dealer:number,playerInTurn?:number}
export interface Round {readonly playerCount:number;readonly dealer:number;player(i:number):string;playerHand(i:number):Card[];drawPile():Deck;discardPile():Deck;playerInTurn():number|undefined;canPlay(i:number):boolean;canPlayAny():boolean;play(i:number,color?:Color):Card;draw():Card|undefined;hasEnded():boolean;winner():number|undefined;score():number|undefined;onEnd(cb:(e:{winner:number})=>void):void;sayUno(i:number):void;catchUnoFailure(a:{accuser:number,accused:number}):boolean;toMemento():RoundMemento}
const okColor=(x:unknown):x is Color=>(colors as readonly unknown[]).includes(x); const mod=(n:number,d:number)=>(n%d+d)%d
class RoundModel implements Round { readonly playerCount:number; readonly dealer:number; private _players:string[]; private hands:Card[][];private drawD:Deck;private disc:Deck;private current:Color;private dir:Direction;private turn:number|undefined;private ended:number|undefined;private callbacks:((e:{winner:number})=>void)[]=[];private missed:Set<number>=new Set();private said:Set<number>=new Set();private activeUno:number|undefined;
 constructor(m:RoundMemento,private shuffler:Shuffler<Card>){if(!m.players||m.players.length<2||m.players.length>10||m.hands.length!==m.players.length)throw Error('Invalid players');this._players=m.players;this.playerCount=m.players.length;this.hands=m.hands.map(h=>createDeckFromMemento(h).toMemento() as Card[]);if(!okColor(m.currentColor)||!['clockwise','counterclockwise'].includes(m.currentDirection)||!Number.isInteger(m.dealer)||m.dealer<0||m.dealer>=this.playerCount||!m.discardPile?.length)throw Error('Invalid round');this.dealer=m.dealer;const initialTop=m.discardPile[0];if(initialTop.color!==undefined&&initialTop.color!==m.currentColor)throw Error('Inconsistent current color');this.current=m.currentColor;this.dir=m.currentDirection;this.drawD=createDeckFromMemento(m.drawPile);this.disc=createDeckFromMemento(m.discardPile);const ws=this.hands.map((h,i)=>h.length===0?i:-1).filter(i=>i>=0);if(ws.length>1)throw Error('Multiple winners');this.ended=ws[0];if(this.ended===undefined){if(!Number.isInteger(m.playerInTurn)||m.playerInTurn!<0||m.playerInTurn!>=this.playerCount)throw Error('Invalid turn');this.turn=m.playerInTurn}}
 private check(i:number){if(!Number.isInteger(i)||i<0||i>=this.playerCount)throw Error('Player out of bounds')};player(i:number){this.check(i);return this._players[i]};playerHand(i:number){this.check(i);return this.hands[i]};drawPile(){return this.drawD};discardPile(){return this.disc};playerInTurn(){return this.turn}
 private matches(c:Card){const t=this.disc.top();return c.type==='WILD'||c.type==='WILD DRAW'||('color'in c&&c.color===this.current)||(c.type==='NUMBERED'&&t?.type==='NUMBERED'&&c.number===t.number)||(c.type!=='NUMBERED'&&c.type!=='WILD'&&c.type!=='WILD DRAW'&&c.type===t?.type)}
 private legal(c:Card,h:Card[]){return this.matches(c)&&(c.type!=='WILD DRAW'||!h.some(x=>'color'in x&&x.color===this.current))};canPlay(index:number){if(this.turn===undefined||!Number.isInteger(index)||index<0||index>=this.hands[this.turn].length)return false;return this.legal(this.hands[this.turn][index],this.hands[this.turn])};canPlayAny(){return this.turn!==undefined&&this.hands[this.turn].some(c=>this.legal(c,this.hands[this.turn]))}
 private advance(n=1){if(this.turn!==undefined)this.turn=mod(this.turn+(this.dir==='clockwise'?n:-n),this.playerCount)};private recycle(){if(this.drawD.size===0&&this.disc.size>1){const top=this.disc.deal()!;const a:Card[]=[];while(this.disc.size>0)a.push(this.disc.deal()!);this.drawD=createDeck(a);this.drawD.shuffle(this.shuffler);this.disc=createDeck([top])}};private take(n:number,p:number){for(let i=0;i<n;i++){this.recycle();const c=this.drawD.deal();if(c)this.hands[p].push(c)}}
 play(index:number,color?:Color){if(this.turn===undefined)throw Error('Round ended');if(!Number.isInteger(index)||index<0||index>=this.hands[this.turn].length)throw Error('Card out of bounds');const p=this.turn;for(const n of this.said)if(n!==p)this.said.delete(n);if(this.activeUno!==undefined&&this.activeUno!==p){this.missed.delete(this.activeUno);this.activeUno=undefined}const h=this.hands[p],c=h[index];if(!this.legal(c,h)||((c.type==='WILD'||c.type==='WILD DRAW')&&!okColor(color))||((c.type!=='WILD'&&c.type!=='WILD DRAW')&&color!==undefined))throw Error('Illegal play');h.splice(index,1);this.disc.add(c);this.missed.delete(p);if(h.length===1&&!this.said.has(p)){this.missed.add(p);this.activeUno=p}this.said.delete(p);if('color'in c)this.current=c.color;else if(c.type==='WILD'||c.type==='WILD DRAW')this.current=color!;if(h.length===0){if(c.type==='DRAW'||c.type==='WILD DRAW'){this.advance();this.take(c.type==='DRAW'?2:4,this.turn!)}this.ended=p;this.turn=undefined;this.callbacks.forEach(cb=>cb({winner:p}));return c}if(c.type==='REVERSE'){this.dir=this.dir==='clockwise'?'counterclockwise':'clockwise';this.advance(this.playerCount===2?0:1)}else if(c.type==='SKIP')this.advance(this.playerCount===2?0:2);else if(c.type==='DRAW'||c.type==='WILD DRAW'){this.advance();this.take(c.type==='DRAW'?2:4,this.turn!);this.advance(this.playerCount===2?0:1)}else this.advance();return c}
 draw(){if(this.turn===undefined)throw Error('Round ended');const p=this.turn;for(const n of this.said)if(n!==p)this.said.delete(n);if(this.activeUno!==undefined&&this.activeUno!==p){this.missed.delete(this.activeUno);this.activeUno=undefined}this.take(1,p);const c=this.hands[p].at(-1);const playable=!!c&&this.legal(c,this.hands[p]);this.recycle();if(!playable)this.advance();return c};hasEnded(){return this.ended!==undefined};winner(){return this.ended};score(){return this.ended===undefined?undefined:this.hands.flat().reduce((s,c)=>s+cardPoints(c),0)};onEnd(cb:(e:{winner:number})=>void){this.callbacks.push(cb)};sayUno(i:number){this.check(i);if(this.turn===undefined)throw Error('Round ended');this.said.add(i);this.missed.delete(i)};catchUnoFailure({accused,accuser}:{accused:number,accuser:number}){this.check(accused);this.check(accuser);if(!this.missed.has(accused))return false;this.missed.delete(accused);this.take(4,accused);return true};toMemento(){return {players:this._players,hands:this.hands.map(h=>h.map(c=>({...c}))),drawPile:this.drawD.toMemento(),discardPile:this.disc.toMemento(),currentColor:this.current,currentDirection:this.dir,dealer:this.dealer,...(this.turn===undefined?{}:{playerInTurn:this.turn})}}
}
export function createRound(players:string[],dealer:number,shuffler:Shuffler<Card>=standardShuffler,cardsPerPlayer=7):Round{if(players.length<2||players.length>10||dealer<0||dealer>=players.length)throw Error('Invalid round');dealer=mod(dealer,players.length);const d=createInitialDeck();d.shuffle(shuffler);const hands=players.map(()=>Array.from({length:cardsPerPlayer},()=>d.deal()!));let top=d.deal()!;while(top.type==='WILD'||top.type==='WILD DRAW'){d.add(top);d.shuffle(shuffler);top=d.deal()!}let turn=mod(dealer+1,players.length);if(top.type==='REVERSE')turn=mod(dealer-1,players.length);if(top.type==='SKIP')turn=mod(dealer+2,players.length);const r=new RoundModel({players,hands,drawPile:d.toMemento(),discardPile:[top],currentColor:'color'in top?top.color:'BLUE',currentDirection:'clockwise',dealer,playerInTurn:turn},shuffler);if(top.type==='DRAW'){(r as any).take(2,turn);(r as any).advance()}return r}
export function createRoundFromMemento(m:RoundMemento,shuffler:Shuffler<Card>=standardShuffler):Round{return new RoundModel(m,shuffler)}
