import { Card, createInitialDeck } from './deck'
import { Randomizer, Shuffler, standardRandomizer, standardShuffler } from '../utils/random_utils'
import { Round, RoundMemento, createRound, createRoundFromMemento } from './round'
export type GameMemento={players:string[],currentRound?:RoundMemento,targetScore:number,scores:number[],cardsPerPlayer:number}
export interface Game{readonly playerCount:number;readonly targetScore:number;player(i:number):string;score(i:number):number;winner():number|undefined;currentRound():Round|undefined;toMemento():GameMemento}
class GameModel implements Game{readonly playerCount:number;readonly targetScore:number;private players:string[];private scores:number[];private round:Round|undefined;private win:number|undefined;private randomizer:Randomizer;private shuffler:Shuffler<Card>;private cardsPerPlayer:number
constructor(m:GameMemento,randomizer:Randomizer,shuffler:Shuffler<Card>){if(!m.players||m.players.length<2||m.targetScore<=0||m.scores.length<m.players.length||m.scores.some(s=>s<0))throw Error('Invalid game');this.players=m.players;this.playerCount=m.players.length;this.targetScore=m.targetScore;this.scores=[...m.scores];this.randomizer=randomizer;this.shuffler=shuffler;this.cardsPerPlayer=m.cardsPerPlayer;const winners=this.scores.map((s,i)=>s>=this.targetScore?i:-1).filter(i=>i>=0);if(winners.length>1)throw Error('Multiple winners');this.win=winners[0];if(!this.win&&this.win!==0){if(!m.currentRound)throw Error('Missing current round');this.round=createRoundFromMemento(m.currentRound,shuffler);this.attach()} }
private attach(){this.round?.onEnd(({winner})=>{this.scores[winner]+=this.round!.score()!;if(this.scores[winner]>=this.targetScore){this.win=winner;this.round=undefined}else{const dealer=this.randomizer(this.playerCount);this.round=createRound(this.players,dealer,this.shuffler,this.cardsPerPlayer);this.attach()}})}
player(i:number){if(i<0||i>=this.playerCount)throw Error('Player out of bounds');return this.players[i]};score(i:number){if(i<0||i>=this.playerCount)throw Error('Player out of bounds');return this.scores[i]};winner(){return this.win};currentRound(){return this.round};toMemento(){return {players:this.players,currentRound:this.round?.toMemento(),targetScore:this.targetScore,scores:[...this.scores],cardsPerPlayer:this.cardsPerPlayer}}
}
export function createGame(players:string[]=['A','B'],targetScore=500,randomizer:Randomizer=standardRandomizer,shuffler:Shuffler<Card>=standardShuffler,cardsPerPlayer=7){const dealer=randomizer(players.length);return new GameModel({players,targetScore,scores:players.map(()=>0),cardsPerPlayer,currentRound:createRound(players,dealer,shuffler,cardsPerPlayer).toMemento()},randomizer,shuffler)}
export function createGameFromMemento(m:GameMemento,randomizer:Randomizer=standardRandomizer,shuffler:Shuffler<Card>=standardShuffler){return new GameModel(m,randomizer,shuffler)}
